name: android
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'source/**'
      - 'express/**'
      - 'test/**'
      - 'project/android/**'
      - '.github/workflows/android.yml'
  pull_request:
    branches: [master]
    paths:
      - 'source/**'
      - 'express/**'
      - 'test/**'
      - 'project/android/**'
      - '.github/workflows/android.yml'
  workflow_dispatch:

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "编译并 apk"
        run: |
            cd project/android
            mkdir build_64
            cd build_64
            ../build_64.sh -DMNN_LOW_MEMORY=true -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true -DMNN_BUILD_LLM=true -DMNN_SUPPORT_TRANSFORMER_FUSE=true -DMNN_ARM82=true -DMNN_USE_LOGCAT=true -DMNN_OPENCL=true -DLLM_SUPPORT_VISION=true -DMNN_BUILD_OPENCV=true -DMNN_IMGCODECS=true -DLLM_SUPPORT_AUDIO=true -DMNN_BUILD_AUDIO=true -DMNN_BUILD_DIFFUSION=ON -DMNN_SEP_BUILD=OFF -DCMAKE_INSTALL_PREFIX=.
            make install
            sleep 1
            cd ../../../apps/Android/MnnLlmChat
            ./gradlew assembleStandardDebug
            sleep 1
            ls app/build/outputs/apk/standard/debug/app-standard-debug.apk
      - name: "上传 apk"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-app-standard-debug.apk
          path: app/build/outputs/apk/standard/debug/app-standard-debug.apk

  upload-release:
    name: upload_to_release
    needs: [android_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: artifact-*
        path: assert
        merge-multiple: true

    - name: show file
      run: ls assert

    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: assert/*.apk
        tags: true
        draft: true
