name: Sync Fork Upstream
on:
  # schedule:
  #   - cron: '0 */6 * * *'  # 每6小时自动执行一次，可自定义频率
  workflow_dispatch: # 支持在Actions页面手动点击按钮触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          github_token: ${{ secrets.PAT }}
          owner: alibaba  # 比如上游仓库是123xuwu/MNN，这里填123xuwu
          base: master          # 上游仓库的目标分支
          head: master          # 你自己Fork仓库要同步的分支
